name: 发布 Docker 镜像 (amd64)
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
jobs:
  build-images:
    name: 推送 Docker 镜像到多个注册表
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
    

      - name: 安装依赖
        run: |
          sudo apt update && sudo apt install -y nodejs npm

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
          
      - name: Login to Docker Registry
        run: | 
         docker version
         # 登录阿里云镜像仓库
         docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          
      - name: 设置容器标签
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi    

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            registry.cn-hangzhou.aliyuncs.com/aabao/chat-api:${{env.IMAGE_TAG}}
            registry.cn-hangzhou.aliyuncs.com/aabao/chat-api:latest
